### ISSUE TITLE
Unable to connect 5 GHZ and showing two wifi

### ISSUE THREAD

**Issue by zainulhasan** [morrownr/8821au-20210708#41]
https://ibb.co/FhLwHWs

sudo uname -a; mokutil --sb-state; lsusb; rfkill list all; dkms status; iw dev
Linux blackbox 5.17.5-76051705-generic #202204271406~1655476786~22.04~62dd706 SMP PREEMPT Fri Jun 17 16 x86_64 x86_64 x86_64 GNU/Linux
SecureBoot disabled
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 04f3:0c5e Elan Microelectronics Corp. ELAN:ARM-M4
Bus 003 Device 003: ID 04f2:b6c0 Chicony Electronics Co., Ltd HP HD Camera
Bus 003 Device 005: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 003 Device 002: ID 2357:011e TP-Link AC600 wireless Realtek RTL8811AU [Archer T2U Nano]
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
0: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
1: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
2: phy1: Wireless LAN
	Soft blocked: no
	Hard blocked: no
rtl8821au/5.12.5.2, 5.17.5-76051705-generic, x86_64: installed
system76/1.0.14~1643391291~22.04~78ede46, 5.17.5-76051705-generic, x86_64: installed
system76_acpi/1.0.2~1640122755~22.04~04145b8, 5.17.5-76051705-generic, x86_64: installed (original_module exists)
system76-io/1.0.2~1655490480~22.04~0217576, 5.17.5-76051705-generic, x86_64: installed
phy#1
	Interface wlxb6b024bf2d82
		ifindex 5
		wdev 0x100000002
		addr b6:b0:24:bf:2d:82
		ssid Wizards V2
		type managed
		txpower 14.00 dBm
	Interface wlxb4b024bf2d82
		ifindex 4
		wdev 0x100000001
		addr b4:b0:24:bf:2d:82
		type managed
		txpower -100.00 dBm
phy#0
	Interface wlp0s20f3
		ifindex 3
		wdev 0x1
		addr 48:51:c5:41:d3:c7
		type managed
		txpower 0.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0

**Comment by morrownr** [comment]
Hi @zainulhasan 

> Unable to connect 5 GHZ

We need to take a look at the module parameters that you are using. Run the following from the driver directory and post the contents of the first `options` line:

$ sudp ./edit-options.sh

I need to know your country to provide a complete answer.

> showing two wifi

You have activated Concurrent Mode. To deactivate:

$ sudo ./remove-driver.sh (depending on the script you used for installation)

$ sudo ./cmode-off.sh

$ sudo ./install-driver.sh

Since users can come here from many places, I like to point them to the site Main Menu as it contains a lot of good information for those of us that use USB WiFi adapters:

https://github.com/morrownr/USB-WiFi

Regards
